name: Continuous integration

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Set up JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run local unit tests
        run: bash ./gradlew test --stacktrace
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        
  #androidTest:
  #  name: Instrumented Tests
  #  runs-on: macOS-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #      with:
  #        submodules: 'recursive'
  #    - name: Set up JDK 1.8
  #      uses: actions/setup-java@v1
  #      with:
  #        java-version: 1.8
  #    - name: Make gradlew executable
  #      run: chmod +x ./gradlew
  #    - name: Run Instrumented Tests
  #      uses: reactivecircus/android-emulator-runner@v1
  #      with:
  #        api-level: 29
  #        arch: x86
  #        disable-animations: true
  #        script: ./gradlew connectedAndroidTest --stacktrace

  apk:
    build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Setup JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: false
        title: ${{ github.sha }}
        files: |
          app/build/outputs/apk/debug/app-debug.apk


