name: Continuous integration

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run local unit tests
        run: ./gradlew test --stacktrace
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0

  apk:
    name: Build APK
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build debug APK
        run: ./gradlew assembleDebug
      - name: List APK files
        run: ls -R app/build/outputs/apk/debug/
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/



